stages:
  - test
  - tutorials
  - deploy

test:
  stage: test
  retry: 1

  image:
    name: lucasmiranda42/deepof:latest
    entrypoint: [""]

  before_script:
    - export PATH="~/.local/pipx/venvs/poetry/bin:$PATH"

  script:
    - coverage run --source deepof -m pytest
    - coverage report -m --include deepof/post_hoc.py,deepof/data.py,deepof/utils.py,deepof/model_utils.py,deepof/annotation_utils.py,deepof/models.py,deepof/hypermodels.py
    - coverage xml -o deepof_cov.xml

  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: deepof_cov.xml

tutorials:
  stage: tutorials

  image:
    name: lucasmiranda42/deepof:latest
    entrypoint: [ "" ]

  before_script:
    - pip install papermill
    - pip install -q -e . --progress-bar off
    - python -m ipykernel install --user --name deepof --display-name "Python (deepof)"
    - curl --output tutorial_files.zip https://datashare.mpcdf.mpg.de/s/knF7t78isQuIAr0/download
    - unzip tutorial_files.zip

  script:
    - papermill docs/source/tutorial_notebooks/deepof_preprocessing_tutorial.ipynb preprocessing_output.ipynb
    - papermill docs/source/tutorial_notebooks/deepof_supervised_tutorial.ipynb supervised_output.ipynb
    - papermill docs/source/tutorial_notebooks/deepof_unsupervised_tutorial.ipynb unsupervised_output.ipynb

deploy:

  stage: deploy
  retry: 1

  image:
    name: python:3.9.14

  script:
    - pip install deepof
